name: Add Pull Request to Data

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print PR
        run: echo ${{github.event.number}}
