name: Add Pull Request to Data

on:
  pull_request:
    types: [opened, reopened, edited, closed]

jobs:

  update_data:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.number}}
      - run: echo ${{ github.repository }}
